### ISSUE TITLE
Track multiple items at once

### ISSUE THREAD

**Issue by snowsecure** [worthbak/inventory-checker-app#23] opened 2022-03-28 15:25 UTC
It would be awesome to be able to track multiple items at once - for instance, a Mac Studio AND a Studio Display.

Great work on this project!

**Comment by worthbak** [comment] 2022-03-29 01:04
Thanks for creating the issue! This looks like a duplicate of #6 - definitely a high priority feature, but something that will require a fair bit of work. Closing this as a dupe - follow #6 for more updates!

**Closed** 2022-03-29 01:04 UTC
