### ISSUE TITLE
Unexpected inventory data found

### ISSUE THREAD

**Issue by bfolberth** [worthbak/inventory-checker-app#88] opened 2022-10-13 06:51 UTC
I'm getting the message `Unexpected inventory data found. Please confirm that the selected store is valid for the selected country.` for an Apple Watch and store Sindelfingen request. Choosing another store seems to work, even shows the inventory for Sindelfingen.

**Comment by worthbak** [comment] 2022-10-13 11:44
Hm, that's odd - I'm unable to reproduce the issue. Can you confirm that your settings look like this (specifically, that you selected Germany as the country)? 

<img width="1491" alt="Screenshot 2022-10-13 at 5 42 23 AM" src="https://user-images.githubusercontent.com/10028428/195587601-aaffe6d2-f18f-4c3f-99c7-22fdee2d1f06.png">

And also that you're running the latest version of the app, `v0.1.6`?

**Comment by bfolberth** [comment] 2022-10-13 12:02
I had this issue yesterday evening a this morning, but it seems to work again. Strange.

**Comment by worthbak** [comment] 2022-10-13 12:15
Got it - sometimes Apple's fulfillment API (which InventoryWatch relies on) can have temporary blips or outages and return bad data for a given product/store combination. I should add some better error-reporting tools to the app that could at least give some more insight into what's happening, and make bug reports easier to fill out. 

In any case, glad the issue resolved itself - I'll close this issue now, but please provide updates if it pops up consistently in the future.

**Closed by worthbak** 2022-10-13 12:15 UTC
Labels: bug
